name: Name.テンプレートの名前
description: Description.テンプレートの説明
title: "[Bug]:タイトルのテンプレート"
labels: 
  - bug
projects: 
  - tanaka-takuto/3
body:
  - type: markdown
    attributes:
      value: |
        # これはマークダウン
        ### マークダウンテスト
        <details><summary>詳細</summary>
          
          詳細を書く
        </details>

  - type: textarea
    attributes:
      label: 目的
      description: 目的を入れる理由
      placeholder: |
        XXのため
    validations:
      required: false

  - type: textarea
    attributes:
      label: 詳細
      description: 詳細を入れる理由
      placeholder: |-
        1. XXXをする
        2. YYYをする
    validations:
      required: false

  - type: textarea
    attributes:
      label: 備考
      description: 備考を入れる理由
      value: |-
        - [project](https://github.com/users/tanaka-takuto/projects/3)
        - [test](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)
